#!/bin/bash

set -e

#SANDBOX=/tmp/plugin
SANDBOX=./builds
rm -rf $SANDBOX
mkdir $SANDBOX

printf "Building OSX...\n"
GOOS=darwin go build -o $SANDBOX/verify-manifest-darwin-$(arch) .

printf "\nBuild summary:\n"
find $SANDBOX -type f -exec file {} \;

printf "\nSHA-1 digests for CF cli plugin repo:\n"
shasum $SANDBOX/verify-manifest*

printf "\nBinaries are located here:\n$SANDBOX\n"
